name = "sparkling-mouse-e6bd"
main = "src/index.ts"
compatibility_date = "2024-01-19"

[vars]
ENVIRONMENT = "production"

# Enable detailed logging
[build]
command = "npm run build"

[dev]
port = 8787

# Enable minimal compatibility mode
compatibility_flags = ["nodejs_compat"]

# Configure logging
[logs]
enabled = true